parameters:
#    o_auth_server.example.class: Acme\OAuthServerBundle\Example

services:
#    o_auth_server.example:
#        class: %o_auth_server.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
